spring:
  main:
    banner-mode: console
  datasource:
    url: jdbc:h2:mem:eshopdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        default_schema:
  data:
    web:
      pageable:
        default-page-size: 3
  security:
    user:
      name: user@skyfly.lt
      password: user
logging:
  level:
    eu:
      codeacademy:
        skyfly:
          config: DEBUG
